// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");

var toList = $$Array.to_list;

var fromList = $$Array.of_list;

exports.toList = toList;
exports.fromList = fromList;
/* No side effect */
