// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function max(_xs) {
  while(true) {
    var xs = _xs;
    if (xs) {
      var match = xs[1];
      var x = xs[0];
      if (match) {
        var y = match[0];
        _xs = List.rev_append(x > y ? /* :: */[
                x,
                /* [] */0
              ] : /* :: */[
                y,
                /* [] */0
              ], match[1]);
        continue ;
      } else {
        return x;
      }
    } else {
      return 0;
    }
  };
}

exports.max = max;
/* No side effect */
