// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_string = require("bs-platform/lib/js/caml_string.js");
var StringReversal = require("./StringReversal.bs.js");

function isPalindrome(s) {
  return s === StringReversal.reverseString(s);
}

function helper(_$staropt$star, s) {
  while(true) {
    var $staropt$star = _$staropt$star;
    var it = $staropt$star !== undefined ? $staropt$star : 0;
    if (it === s.length) {
      return true;
    } else if (Caml_string.get(s, it) === Caml_string.get(s, (s.length - 1 | 0) - it | 0)) {
      _$staropt$star = it + 1 | 0;
      continue ;
    } else {
      return false;
    }
  };
}

function isPalindrome2(s) {
  return helper(undefined, s);
}

exports.isPalindrome = isPalindrome;
exports.helper = helper;
exports.isPalindrome2 = isPalindrome2;
/* No side effect */
