// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Char = require("bs-platform/lib/js/char.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");

function reverse_string(_$staropt$star, _$staropt$star$1, s) {
  while(true) {
    var $staropt$star = _$staropt$star$1;
    var $staropt$star$1 = _$staropt$star;
    var it = $staropt$star$1 !== undefined ? $staropt$star$1 : 0;
    var r = $staropt$star !== undefined ? $staropt$star : "";
    var match = it < s.length;
    if (match) {
      _$staropt$star$1 = Char.escaped(Caml_string.get(s, it)) + r;
      _$staropt$star = it + 1 | 0;
      continue ;
    } else {
      return r;
    }
  };
}

var Helpers = /* module */[/* reverse_string */reverse_string];

function reverseString(s) {
  return reverse_string(undefined, undefined, s);
}

exports.Helpers = Helpers;
exports.reverseString = reverseString;
/* No side effect */
